name: build-docker

on:
  workflow_dispatch:

jobs:

  static:
    name: Static binaries
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ORG_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout lxd code
        uses: actions/checkout@v3
        with:
          repository: lxc/lxd
          ref: 'lxd-5.8'
          path: ./app

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./Dockerfile
          push: push
          tags: |
            lxd:${{ github.run_number }}    