name: build-docker

on:
  workflow_dispatch:
    inputs:
      release: 
        type: choice
        description: Release
        options:
        - "5.8"

jobs:

  static:
    name: Static binaries
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ORG_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout lxd code
        uses: actions/checkout@v3
        with:
          repository: lxc/lxd
          ref: "lxd-${{ github.event.inputs.release }}"
          path: ./app

      #- name: Use custom make file 
      #  run: cp make ./app/

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./Dockerfile
          push: false
          tags: |
            ${{ secrets.ORG_DOCKERHUB_USERNAME }}/lxd:${{ github.run_number }}    

      - name: Fetch binary files 
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.ORG_DOCKERHUB_USERNAME }}/lxd:${{ github.run_number }}
          options: -v ${{ github.workspace }}/output:/output
          run: |
            cp /go/bin/lxc /output/
            cp /go/bin/lxc-to-lxd /output/
            cp /go/bin/lxd /output/
            cp /go/bin/lxd-agent /output/
            cp /go/bin/lxd-benchmark /output/ 
            cp /go/bin/lxd-migrate /output/
            cp /go/bin/lxd-user /output/
            cp /go/bin/fuidshift /output/
            cp /go/bin/macaroon-identity /output/
            cp /go/deps/dqlite/.libs/libdqlite.so.0 /output/

      - name: Attach artifacts to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/output/*"
          name: lxd-${{ github.event.inputs.release }} binary files
          tag: ${{ github.event.inputs.release }}
          allowUpdates: true
          replacesArtifacts: true
          body: |
            **Source:** https://github.com/lxc/lxd/releases/tag/lxd-${{ github.event.inputs.release }}
          token: ${{ secrets.ORG_RELEASE_UPDATER }}